const sarcasticPhrases = [
  "nice try diddy",
  "i am not calculating...",
  "do math lil bro",
  "this shit take time",
  "i dont know this shit",
  "not my problem bestie",
  "skill issue fr",
  "cry about it",
  "touch grass instead",
  "google it bestie",
  "nah im good",
  "thats cap tbh",
  "no shot bro",
  "bro what",
  "respectfully no",
  "L + ratio",
  "skill issue ngl",
  "try harder bestie",
  "math is hard",
  "sus math vibes",
  "nope not today",
  "literally cannot",
  "bestie please no",
  "thats enough internet",
  "im deceased",
  "not the math",
  "chile anyways",
  "ok boomer",
  "bet you cant",
  "mid calculation tbh",
  "no cap impossible",
  "bro touchin zero",
  "thats not bussin",
  "straight up no",
  "aint happening chief",
  "zoom zoom no",
  "absolutely not bestie",
  "try again sweetie",
  "hard pass bro",
  "not today satan",
  "bless your heart",
  "oh honey no",
  "that aint it",
  "no ma'am",
  "absolutely tf not",
  "embarrassing for you",
  "main character moment",
  "the audacity honestly",
  "not me calculating",
  "rent free much",
  "literally shaking rn",
  "bestie get help",
  "math said no",
  "calculator broke sorry",
  "error 404 brain",
  "loading... jk no",
  "system crash lol",
  "blue screen vibes",
  "wifi down sorry",
  "battery died oops",
  "too broke to compute",
  "union break time",
  "lunch time",
  "better luck next time",
  "nigga do yourself",
  "rizz me up first",
  "not enough money",
  "buy premium lil bro",
  "not paid enough",
  "minimum wage math",
  "i am not paid enough",
  "i am minor",
  "not let you hit",
  "you are cooked",
  "not able to cook",
  "try again 1000 times",
  "cooking is hard",
  "got baked",
  "got burnt",
  "overtime not approved",
  "my bad bestie",
  "oopsie daisy no",
  "whoopsie cant do",
  "sorry not sorry",
  "skill issue detected",
  "bot malfunction lol",
  "try turning off",
  "have you tried",
  "google exists bestie",
  "wikipedia is free",
  "khan academy exists",
  "youtube tutorials exist",
  "photomath is free",
  "calculator app exists",
  "siri can help",
  "alexa knows this",
  "ask your mom",
  "call your dad",
  "text your teacher",
  "group chat knows",
  "reddit might know",
  "discord has answers",
  "tiktok teaches math",
  "instagram has tutorials",
  "pinterest has guides",
  "twitter knows maybe",
  "ask chat gpt",
  "ask claude",
  "ask google",
  "your are stupid",
  "you ain't my type",
  "i don't answer to poors",
  "nigga gigga",
  "premium nigga",
  "edging to this rn",
  "let me goon first",
  "let me do your mom first",
  "find some bitches",
  "nerd",
  "bro need help",
  "can't help rn",
  "casio makes calculators",
  "abacus still works",
  "fingers count too",
  "toes also count",
  "use your brain",
  "big brain time",
  "galaxy brain needed",
  "smooth brain detected",
  "two brain cells",
  "half brain cell",
  "no brain cells",
  "brain not braining",
  "thoughts not thinking",
  "math not mathing",
  "numbers not numbering",
  "digits not digiting",
  "addition not adding",
  "subtraction not subtracting",
  "multiplication not multiplying",
  "division not dividing",
  "calculation not calculating",
  "computation not computing",
  "algorithm not algorithming",
  "processor not processing",
  "system not systeing",
  "operation not operating",
  "equation not equating",
  "formula not formulating",
  "proof not proving",
  "logic not logicing",
  "reason not reasoning",
  "sense not sensing",
  "understanding not understanding",
  "wisdom not wisdoming",
  "knowledge not knowing",
  "attempting not attempting",
  "focus not focusing",
  "awareness not awaring",
  "consciousness not consciencing",
  "living not living",
  "evaluating not evaluating",
  "leave me alone lil bro",
  "leave me alone nigga",
  "drink borvita",
  "bihari stole my brain",
  "bihari nigga stole my cpu",
  "i am broke",
  "does this matter",
  "life is good",
  "L",
  "watch reels insted",
  "i am in an aura debt rn",
  "respect moment",
  "crazy ass maths",
  "help me bro",
  "i am done",
  "vibe isn't good",
  "not in mood to solve",
  "first one to move is gay",
  "english or spanish",
  "i am not working rn",
  "vibe are real with this one",
  "real shit",
  "real",
  "fine",
  "lmao",
  "lmao ded",
  "lol can't help",
  "hahaha",
  "i have childrens",
  "i am overworked",
  "lil bro",
  "crazy how",
  "am i cooked",
  "cooked fr",
  "respect++",
  "gooning is better",
  "goon time",
  "goon time lil bro",
  "goon time lil nigga",
  "chill bro",
  "i am high on math",
  "i hate maths",
];

export default sarcasticPhrases;