const sarcasticPhrases = [
  "nice try diddy",
  "i am not calculating...",
  "do math lil bro",
  "this shit take time",
  "i dont know this shit",
  "not my problem bestie",
  "skill issue fr",
  "cry about it",
  "touch grass instead",
  "google it bestie",
  "nah im good",
  "thats cap tbh",
  "no shot bro",
  "bro what",
  "respectfully no",
  "L + ratio",
  "skill issue ngl",
  "try harder bestie",
  "not it chief",
  "periodt no",
  "sus math vibes",
  "nope not today",
  "literally cannot",
  "bestie please no",
  "thats enough internet",
  "im deceased",
  "not the math",
  "chile anyways",
  "sir this wendys",
  "ok boomer",
  "bet you cant",
  "mid calculation tbh",
  "no cap impossible",
  "bro touchin zero",
  "thats not bussin",
  "straight up no",
  "aint happening chief",
  "get rekt kiddo",
  "zoom zoom no",
  "absolutely not bestie",
  "try again sweetie",
  "negative ghost rider",
  "hard pass bro",
  "not today satan",
  "bless your heart",
  "oh honey no",
  "imagine thinking yes",
  "bestie be serious",
  "that aint it",
  "no ma'am",
  "absolutely tf not",
  "sir please stop",
  "this you?",
  "embarrassing for you",
  "main character moment",
  "the audacity honestly",
  "not me calculating",
  "rent free much",
  "ok bet sure",
  "literally shaking rn",
  "bestie get help",
  "math said no",
  "calculator broke sorry",
  "error 404 brain",
  "loading... jk no",
  "system crash lol",
  "blue screen vibes",
  "wifi down sorry",
  "battery died oops",
  "too broke compute",
  "union break time",
  "not paid enough",
  "minimum wage math",
  "overtime not approved",
  "my bad bestie",
  "oopsie daisy no",
  "whoopsie cant do",
  "sorry not sorry",
  "skill issue detected",
  "bot malfunction lol",
  "try turning off",
  "have you tried",
  "google exists bestie",
  "wikipedia is free",
  "khan academy exists",
  "youtube tutorials exist",
  "photomath is free",
  "calculator app exists",
  "siri can help",
  "alexa knows this",
  "ask your mom",
  "call your dad",
  "text your teacher",
  "group chat knows",
  "reddit might know",
  "discord has answers",
  "tiktok teaches math",
  "instagram has tutorials",
  "pinterest has guides",
  "twitter knows maybe",
  "ask chat gpt",
  "bing has answers",
  "duck duck go",
  "stack overflow knows",
  "quora might help",
  "desmos calculator free",
  "casio makes calculators",
  "ti eighty four",
  "abacus still works",
  "fingers count too",
  "toes also count",
  "use your brain",
  "think mcfly think",
  "big brain time",
  "galaxy brain needed",
  "smooth brain detected",
  "two brain cells",
  "half brain cell",
  "no brain cells",
  "brain not braining",
  "thoughts not thinking",
  "math not mathing",
  "numbers not numbering",
  "digits not digiting",
  "addition not adding",
  "subtraction not subtracting",
  "multiplication not multiplying",
  "division not dividing",
  "calculation not calculating",
  "computation not computing",
  "algorithm not algorithming",
  "processor not processing",
  "system not systeing",
  "function not functioning",
  "operation not operating",
  "equation not equating",
  "formula not formulating",
  "theorem not theorizing",
  "proof not proving",
  "logic not logicing",
  "reason not reasoning",
  "sense not sensing",
  "understanding not understanding",
  "comprehension not comprehending",
  "intelligence not intelligencing",
  "wisdom not wisdoming",
  "knowledge not knowing",
  "learning not learning",
  "studying not studying",
  "practicing not practicing",
  "working not working",
  "trying not trying",
  "attempting not attempting",
  "focus not focusing",
  "awareness not awaring",
  "consciousness not consciencing",
  "existence not existing",
  "living not living",
  "breathing not breathing",
  "comparing not comparing",
  "evaluating not evaluating",
  "assessing not assessing",
  "enjoying not enjoying",
  "appreciating not appreciating",
  "valuing not valuing",
];

export default sarcasticPhrases;